# Generated by Django 2.2.11 on 2021-04-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup', models.BooleanField(default=False, help_text="Designe la permission de s'inscrire sur le site.", verbose_name='Inscription')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_site', to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'abstract': False,
            },
        ),
    ]
